name: check-build

on: [push]

jobs:
  build-linux-gcc:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo ./library_installers/install_libraries.sh
      - name: Test
        run: |
          ./test.sh
